variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress

test:
  image: cypress/base:10
  stage: test
  script:
    - npm ci
    # print CI environment variables
    - $(npm bin)/print-env CI
    - npm run cy:verify
    - npm run start:ci &
    - npm run e2e:record