variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress

test:
  image: cypress/base:10
  stage: test
  script:
    - npm ci
    - npm install --save-dev cypress
    - npm start &
    - sleep 15
    - npm run cy:run