version: 2
jobs:
  test:
    docker:
      - image: cypress/base:10
    branch:
      - master
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          command: npm start
          background: true
      - run:
          name: Wait
          command: sleep 15      
      - run: npm run cy:run

workflows:
  version: 2
  build:
    jobs:
      - test
      